$("#save").click(function(){
    $.ajax({
        URL:"db.php",
        type:"post",
        data:$("#frm").serialize(),
        success:function(d){
            alert(d);
        }
    });
});