n=input("Hotel name:")
s=input("Customer name:")
b=int(input("Billno:"))
d1=int(input("Idly:"))
d2=int(input("Dosa:"))
d3=int(input("Chappathi:"))
total=d1+d2+d3
print("Hotel name:",n)
print("customer name:",s)
print("Billno:",b)
print("Idly:",d1)
print("Dosa:",d2)
print("Chappathi:",d3)
print("Total:",total)
