n=int(input("Train no:"))
m=input("Train name:")
p=input("Destination to:")
u=int(input("Seat no:"))
t=int(input("Amount:"))
print("Train no:",n)
print("Train name:",m)
print("Destination to:",p)
print("Seat no:",u)
print("Amount:",t)
